name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Install Dependencies Locally
      - name: Install Dependencies
        run: npm install

      # Step 4: Archive Application
      - name: Archive Application
        run: zip -r app.zip . -x "*.git*"

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "app.zip"
          target: "/home/ubuntu/app.zip"

      # Step 6: SSH into EC2 and Restart Application
      - name: Restart Application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            sudo apt update
            sudo apt install -y unzip
            mkdir -p /home/ubuntu/app
            unzip -o /home/ubuntu/app.zip -d /home/ubuntu/app
            cd /home/ubuntu/app
            npm install
            pm2 restart app.js || pm2 start app.js
